apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 404851169972.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 404851169972.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 19527f24
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
